# rabbitmq配置


server:
  port: 7008
  ssl:
    key-store: classpath:fzulyt.fun.jks
    key-store-password: 4y004x18ha2
    enabled: true
  servlet:
    context-path: /thread


eureka:
  client:
    service-url:
      defaultZone: http://localhost:5060/eureka/eureka
  #eureka:
  #  client:
  #    service-url:
  #      defaultZone: http://localhost:7070/eureka/eureka
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  application:
    name: product-server
  datasource:
    url: jdbc:mysql://localhost:3306/summer?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    #type: com.alibaba.druid.pool.DruidDataSource
  redis:
    cluster:
      #设置key的生存时间，当key过期时，它会被自动删除；
      expire-seconds: 120
      #设置命令的执行时间，如果超过这个时间，则报错;
      command-timeout: 5000
      #设置redis集群的节点信息，其中namenode为域名解析，通过解析域名来获取相应的地址;
      nodes: namenode22:6379,datanode23:6379,datanode24:6379,datanode25:6379,datanode26:6379,datanode27:6379
  main:
    allow-bean-definition-overriding: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql
  returnPageInfo: check

