server:
  servlet:
  #  定义项目的访问访问路径
    context-path: /consumer
    #定义端口号
  port: 7002
spring:
  redis:
    cluster:
      #设置key的生存时间，当key过期时，它会被自动删除；
      expire-seconds: 120
      #设置命令的执行时间，如果超过这个时间，则报错;
      command-timeout: 5000
      #设置redis集群的节点信息，其中namenode为域名解析，通过解析域名来获取相应的地址;
      nodes: namenode22:6379,datanode23:6379,datanode24:6379,datanode25:6379,datanode26:6379,datanode27:6379
  application:
  #定义应用名称，即服务名称
    name: consumer-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5060/eureka/eureka
